package yi

import (
	"testing"
)

func qian(gx map[string]*GuaXiang) map[string]*GuaXiang {
	gx["乾坤"] = &GuaXiang{
		ShangGua:        "乾為天",
		ShangShu:        0x00,
		XiaGua:          "坤為地",
		XiaShu:          0x07,
		GuaXiang:        "否",
		GuaMing:         "天地否",
		ChuYao:          "拔茅貞吉，志在君也",
		ChuYaoJiXiong:   "平",
		ErYao:           "大人否，享，不亂群也",
		ErYaoJiXiong:    "平",
		SanYao:          "包羞，位不當也",
		SanYaoJiXiong:   "凶",
		SiYao:           "有命無咎，志行也",
		SiYaoJiXiong:    "吉",
		WuYao:           "大人之吉，位正當也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "否終則傾，何可長也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾艮"] = &GuaXiang{
		ShangGua:        "乾為天",
		ShangShu:        0x00,
		XiaGua:          "艮為山",
		XiaShu:          0x06,
		GuaXiang:        "遁",
		GuaMing:         "天山遁",
		ChuYao:          "遁尾之厲，不往何災也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "執用黃牛，固志也",
		ErYaoJiXiong:    "平",
		SanYao:          "系遁之厲，有疾憊也。畜臣妾吉，不可大事也",
		SanYaoJiXiong:   "平",
		SiYao:           "君子好遁，小人否也",
		SiYaoJiXiong:    "平",
		WuYao:           "嘉遁貞吉，以正志也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "肥遁無不利，無所疑也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
		YongJiXiong:     "",
	}
	gx["乾坎"] = &GuaXiang{
		ShangGua:        "乾為天",
		ShangShu:        0x00,
		XiaGua:          "坎為水",
		XiaShu:          0x05,
		GuaXiang:        "訟",
		GuaMing:         "天水訟",
		ChuYao:          "不永所事，訟不可長也；雖小有言，其辯明也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "不克訟，歸而逋也；自下訟上，患至掇也",
		ErYaoJiXiong:    "平",
		SanYao:          "食舊德，從上吉也",
		SanYaoJiXiong:   "平",
		SiYao:           "復即命，渝安貞，吉，不失也",
		SiYaoJiXiong:    "吉",
		WuYao:           "訟，元吉，以中正也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "以訟受服，亦不足敬也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾巽"] = &GuaXiang{
		ShangGua:        "乾為天",
		ShangShu:        0x00,
		XiaGua:          "巽為風",
		XiaShu:          0x04,
		JiXiong:         "",
		GuaXiang:        "姤",
		GuaMing:         "天風姤",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "繫於金柅，柔道牽也",
		ChuYaoJiXiong:   "平",
		ErYao:           "包有魚，義不及賓也",
		ErYaoJiXiong:    "平",
		SanYao:          "其行次且，行未牽也",
		SanYaoJiXiong:   "凶",
		SiYao:           "無魚之凶，遠民也",
		SiYaoJiXiong:    "凶",
		WuYao:           "九五含章，中正也；有隕自天，志不捨命也",
		WuYaoJiXiong:    "平",
		ShangYao:        "姤其角，上窮吝也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾震"] = &GuaXiang{
		ShangGua:        "乾為天",
		ShangShu:        0x00,
		XiaGua:          "震為雷",
		XiaShu:          0x03,
		GuaXiang:        "無妄",
		GuaMing:         "天雷無妄",
		ChuYao:          "無妄之往，得志也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "不耕穫，未富也",
		ErYaoJiXiong:    "吉",
		SanYao:          "行人得牛，邑人災也",
		SanYaoJiXiong:   "凶",
		SiYao:           "可貞無咎，固有之也",
		SiYaoJiXiong:    "平",
		WuYao:           "無妄之藥，不可試也",
		WuYaoJiXiong:    "平",
		ShangYao:        "無妄之行，窮之災也",
		ShangYaoJiXiong: "平",
	}

	gx["乾離"] = &GuaXiang{
		ShangGua:        "乾為天",
		ShangShu:        0x00,
		XiaGua:          "離為火",
		XiaShu:          0x02,
		JiXiong:         "",
		GuaXiang:        "同人",
		GuaMing:         "天火同人",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "出門同人，又誰咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "同人於宗，吝道也",
		ErYaoJiXiong:    "凶",
		SanYao:          "伏戎於莽，敵剛也，三歲不興，安行也",
		SanYaoJiXiong:   "凶",
		SiYao:           "乘其墉，義弗克也，其吉，則困而反則也",
		SiYaoJiXiong:    "平",
		WuYao:           "同人之先，以中直也。大師相遇，言相剋也",
		WuYaoJiXiong:    "平",
		ShangYao:        "同人於郊，志未得也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾兌"] = &GuaXiang{
		ShangGua:        "乾為天",
		ShangShu:        0x00,
		XiaGua:          "兌為澤",
		XiaShu:          0x01,
		GuaXiang:        "履",
		GuaMing:         "天澤履",
		ChuYao:          "素履之往，獨行願也",
		ChuYaoJiXiong:   "平",
		ErYao:           "幽人貞吉，中不自亂也",
		ErYaoJiXiong:    "平",
		SanYao:          "眇能視，不足以有明也。跛能履，不足以與行也。咥人之凶，位不當也。武人為於大君，志剛也",
		SanYaoJiXiong:   "凶",
		SiYao:           "愬愬終吉，志行也",
		SiYaoJiXiong:    "平",
		WuYao:           "夬履貞厲。位正當也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "元吉在上，大有慶也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["乾乾"] = &GuaXiang{
		ShangGua:        "乾為天",
		ShangShu:        0x00,
		XiaGua:          "乾為天",
		XiaShu:          0x00,
		JiXiong:         "吉",
		GuaXiang:        "乾",
		GuaMing:         "乾為天",
		GuaYi:           "元亨，利貞",
		GuaYun:          "大哉乾元，萬物資始，乃統天。雲行雨施，品物流形。大明始終，六位時成，時乘六龍以御天。乾道變化，各正性命，保合大和，乃利貞。首出庶物，萬國鹹寧",
		XiangYue:        "天行健，君子以自強不息",
		FuHao:           "䷀",
		ChuYao:          "潛龍勿用，陽在下也",
		ChuYaoJiXiong:   "平",
		ErYao:           "見龍在田，德施普也",
		ErYaoJiXiong:    "吉",
		SanYao:          "終日乾乾，反覆道也",
		SanYaoJiXiong:   "平",
		SiYao:           "或躍在淵，進無咎也",
		SiYaoJiXiong:    "平",
		WuYao:           "飛龍在天，大人造也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "亢龍有悔，盈不可久也",
		ShangYaoJiXiong: "平",
		Yong:            "天德不可為首也",
		YongJiXiong:     "-",
	}

	return gx
}

func kun(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["坤坤"] = &GuaXiang{
		ShangGua:        "坤為地",
		ShangShu:        0x07,
		XiaGua:          "坤為地",
		XiaShu:          0x07,
		JiXiong:         "",
		GuaXiang:        "坤",
		GuaMing:         "坤為地",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "履霜堅冰，陰始凝也。馴致其道，至堅冰也",
		ChuYaoJiXiong:   "平",
		ErYao:           "六二之動，直以方也；不習無不利，地道光也",
		ErYaoJiXiong:    "吉",
		SanYao:          "含章可貞，以時發也；或從王事，知光大也",
		SanYaoJiXiong:   "平",
		SiYao:           "括囊無咎，慎不害也",
		SiYaoJiXiong:    "平",
		WuYao:           "黃裳元吉，文在中也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "龍戰於野，其道窮也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坤艮"] = &GuaXiang{
		ShangGua:        "坤為地",
		ShangShu:        0x07,
		XiaGua:          "艮為山",
		XiaShu:          0x06,
		JiXiong:         "吉",
		GuaXiang:        "謙",
		GuaMing:         "地山謙",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "地中有山，謙。君子以裒多益寡，稱物平施",
		FuHao:           "",
		ChuYao:          "謙謙君子，卑以自牧也",
		ChuYaoJiXiong:   "平",
		ErYao:           "鳴謙貞吉，中心得也",
		ErYaoJiXiong:    "吉",
		SanYao:          "勞謙君子，萬民服也",
		SanYaoJiXiong:   "吉",
		SiYao:           "無不利，撝謙，不違則也",
		SiYaoJiXiong:    "吉",
		WuYao:           "利用侵伐，徵不服也",
		WuYaoJiXiong:    "平",
		ShangYao:        "鳴謙，志未得也；可用行師，徵邑國也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坤坎"] = &GuaXiang{
		ShangGua:        "坤為地",
		ShangShu:        0x07,
		XiaGua:          "坎為水",
		XiaShu:          0x05,
		GuaXiang:        "師",
		GuaMing:         "地水師",
		ChuYao:          "師出以律，失律凶也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "在師中吉，承天寵也，王三錫命，懷萬邦也",
		ErYaoJiXiong:    "吉",
		SanYao:          "師或輿屍，大無功也",
		SanYaoJiXiong:   "凶",
		SiYao:           "左次無咎，未失常也",
		SiYaoJiXiong:    "平",
		WuYao:           "長子帥師，以中行也；弟子輿屍，使不當也",
		WuYaoJiXiong:    "平",
		ShangYao:        "大君有命，以正功也；小人勿用，必亂邦也",
		ShangYaoJiXiong: "平",
	}

	gx["坤巽"] = &GuaXiang{
		ShangGua:        "坤為地",
		ShangShu:        0x07,
		XiaGua:          "巽為風",
		XiaShu:          0x04,
		GuaXiang:        "升",
		GuaMing:         "地風升",
		ChuYao:          "允升大吉，上合志也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "九二之孚，有喜也",
		ErYaoJiXiong:    "平",
		SanYao:          "升虛邑，無所疑也",
		SanYaoJiXiong:   "平",
		SiYao:           "王用亨於岐山，順事也",
		SiYaoJiXiong:    "吉",
		WuYao:           "貞吉升階，大得志也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "冥升在上，消不富也",
		ShangYaoJiXiong: "平",
	}

	gx["坤震"] = &GuaXiang{
		ShangGua:        "坤為地",
		ShangShu:        0x07,
		XiaGua:          "震為雷",
		XiaShu:          0x03,
		JiXiong:         "",
		GuaXiang:        "復",
		GuaMing:         "地雷復",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "不遠之復，以修身也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "休復之吉，以下仁也",
		ErYaoJiXiong:    "吉",
		SanYao:          "頻復之厲，義無咎也",
		SanYaoJiXiong:   "平",
		SiYao:           "中行獨復，以從道也",
		SiYaoJiXiong:    "平",
		WuYao:           "敦復無悔，中以自考也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "迷復之凶，反君道也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坤離"] = &GuaXiang{
		ShangGua:        "坤為地",
		ShangShu:        0x07,
		XiaGua:          "離為火",
		XiaShu:          0x02,
		GuaXiang:        "明夷",
		GuaMing:         "地火明夷",
		ChuYao:          "君子於行，義不食也",
		ChuYaoJiXiong:   "平",
		ErYao:           "六二之吉，順以則也",
		ErYaoJiXiong:    "吉",
		SanYao:          "南狩之志，乃大得也",
		SanYaoJiXiong:   "平",
		SiYao:           "入於左腹，獲心意也",
		SiYaoJiXiong:    "平",
		WuYao:           "箕子之貞，明不可息也",
		WuYaoJiXiong:    "平",
		ShangYao:        "初登於天，照四國也。後入於地，失則也",
		ShangYaoJiXiong: "凶",
	}

	gx["坤兌"] = &GuaXiang{
		ShangGua:        "坤為地",
		ShangShu:        0x07,
		XiaGua:          "兌為澤",
		XiaShu:          0x01,
		GuaXiang:        "臨",
		GuaMing:         "地澤臨",
		ChuYao:          "鹹臨貞吉，志行正也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "鹹臨，吉無不利，未順命也",
		ErYaoJiXiong:    "吉",
		SanYao:          "甘臨，位不當也。即憂之，咎不長也",
		SanYaoJiXiong:   "凶",
		SiYao:           "至臨無咎，位當也",
		SiYaoJiXiong:    "平",
		WuYao:           "大君之宜，行中之謂也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "敦臨之吉，志在內也",
		ShangYaoJiXiong: "吉",
	}

	gx["坤乾"] = &GuaXiang{
		ShangGua:        "坤為地",
		ShangShu:        0x07,
		XiaGua:          "乾為天",
		XiaShu:          0x00,
		GuaXiang:        "泰",
		GuaMing:         "地天泰",
		ChuYao:          "拔茅徵吉，志在外也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "包荒，得尚於中行，以光大也",
		ErYaoJiXiong:    "吉",
		SanYao:          "無往不復，天地際也",
		SanYaoJiXiong:   "平",
		SiYao:           "翩翩不富，皆失實也；不戒以孚，中心願也",
		SiYaoJiXiong:    "平",
		WuYao:           "以祉元吉，中以行願也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "城復於隍，其命亂也",
		ShangYaoJiXiong: "凶",
	}
	return gx
}

func gen(gx map[string]*GuaXiang) map[string]*GuaXiang {
	gx["艮坤"] = &GuaXiang{
		ShangGua:        "艮為山",
		ShangShu:        0x06,
		XiaGua:          "坤為地",
		XiaShu:          0x07,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "山地剝",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "剝床以足，以滅下也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "剝床以辨，未有與也",
		ErYaoJiXiong:    "凶",
		SanYao:          "剝之無咎，失上下也",
		SanYaoJiXiong:   "平",
		SiYao:           "剝床以膚，切近災也",
		SiYaoJiXiong:    "凶",
		WuYao:           "以宮人寵，終無尤也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "君子得輿，民所載也；小人剝廬，終不可用也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["艮艮"] = &GuaXiang{
		ShangGua:        "艮為山",
		ShangShu:        0x06,
		XiaGua:          "艮為山",
		XiaShu:          0x06,
		GuaMing:         "艮為山",
		ChuYao:          "艮其趾，未失正也",
		ChuYaoJiXiong:   "平",
		ErYao:           "不拯其隨，未退聽也",
		ErYaoJiXiong:    "凶",
		SanYao:          "艮其限，危薰心也",
		SanYaoJiXiong:   "凶",
		SiYao:           "艮其身，止諸躬也",
		SiYaoJiXiong:    "平",
		WuYao:           "艮其輔，以中正也",
		WuYaoJiXiong:    "平",
		ShangYao:        "敦艮之吉，以厚終也",
		ShangYaoJiXiong: "吉",
	}

	gx["艮坎"] = &GuaXiang{
		ShangGua:        "艮為山",
		ShangShu:        0x06,
		XiaGua:          "坎為水",
		XiaShu:          0x05,
		GuaMing:         "山水蒙",
		ChuYao:          "利用刑人，以正法也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "子克家，剛柔接也",
		ErYaoJiXiong:    "吉",
		SanYao:          "勿用娶女，行不順也",
		SanYaoJiXiong:   "凶",
		SiYao:           "困蒙之吝，獨遠實也",
		SiYaoJiXiong:    "凶",
		WuYao:           "童蒙之吉，順以巽也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "利用禦寇，上下順也",
		ShangYaoJiXiong: "平",
	}
	gx["艮巽"] = &GuaXiang{
		ShangGua:        "艮為山",
		ShangShu:        0x06,
		XiaGua:          "巽為風",
		XiaShu:          0x04,
		GuaMing:         "山風蠱",
		ChuYao:          "幹父之蠱，意承考也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "幹母之蠱，得中道也",
		ErYaoJiXiong:    "平",
		SanYao:          "幹父之蠱，終無咎也",
		SanYaoJiXiong:   "凶",
		SiYao:           "裕父之蠱，往未得也",
		SiYaoJiXiong:    "凶",
		WuYao:           "幹父之蠱，承以德也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "不事王侯，志可則也",
		ShangYaoJiXiong: "平",
	}
	gx["艮震"] = &GuaXiang{
		ShangGua:        "艮為山",
		ShangShu:        0x06,
		XiaGua:          "震為雷",
		XiaShu:          0x03,
		GuaMing:         "山雷頤",
		ChuYao:          "觀我朵頤，亦不足貴也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "六二徵凶，行失類也",
		ErYaoJiXiong:    "凶",
		SanYao:          "十年勿用，道大悖也",
		SanYaoJiXiong:   "凶",
		SiYao:           "顛頤之吉，上施光也",
		SiYaoJiXiong:    "吉",
		WuYao:           "居貞之吉，順以從上也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "由頤厲吉，大有慶也",
		ShangYaoJiXiong: "吉",
	}

	gx["艮離"] = &GuaXiang{
		ShangGua:        "艮為山",
		ShangShu:        0x06,
		XiaGua:          "離為火",
		XiaShu:          0x02,
		GuaMing:         "山火賁",
		ChuYao:          "舍車而徒，義弗乘也",
		ChuYaoJiXiong:   "平",
		ErYao:           "賁其須，與上興也",
		ErYaoJiXiong:    "平",
		SanYao:          "永貞之吉，終莫之陵也",
		SanYaoJiXiong:   "吉",
		SiYao:           "六四當位疑也。匪寇婚媾，終無尤也",
		SiYaoJiXiong:    "平",
		WuYao:           "六五之吉，有喜也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "白賁無咎，上得志也",
		ShangYaoJiXiong: "平",
	}

	gx["艮兌"] = &GuaXiang{
		ShangGua:        "艮為山",
		ShangShu:        0x06,
		XiaGua:          "兌為澤",
		XiaShu:          0x01,
		GuaMing:         "山澤損",
		ChuYao:          "已事遄往，尚合志也",
		ChuYaoJiXiong:   "平",
		ErYao:           "九二利貞，中以為志也",
		ErYaoJiXiong:    "凶",
		SanYao:          "一人行，三則疑也",
		SanYaoJiXiong:   "平",
		SiYao:           "損其疾，亦可喜也",
		SiYaoJiXiong:    "平",
		WuYao:           "六五元吉，自上佑也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "弗損益之，大得志也",
		ShangYaoJiXiong: "吉",
	}
	gx["艮乾"] = &GuaXiang{
		ShangGua:        "艮為山",
		ShangShu:        0x06,
		XiaGua:          "乾為天",
		XiaShu:          0x00,
		GuaMing:         "山天大畜",
		ChuYao:          "有厲利已，不犯災也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "輿說輹，中無尤也",
		ErYaoJiXiong:    "凶",
		SanYao:          "利有攸往，上合志也",
		SanYaoJiXiong:   "平",
		SiYao:           "六四元吉，有喜也",
		SiYaoJiXiong:    "吉",
		WuYao:           "六五之吉，有慶也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "何天之衢，道大行也",
		ShangYaoJiXiong: "吉",
	}

	gx["坎坤"] = &GuaXiang{
		ShangGua:        "坎為水",
		ShangShu:        0x05,
		XiaGua:          "坤為地",
		XiaShu:          0x07,
		GuaMing:         "水地比",
		ChuYao:          "比之初六，有它吉也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "比之自內，不自失也",
		ErYaoJiXiong:    "吉",
		SanYao:          "比之匪人，不亦傷乎",
		SanYaoJiXiong:   "凶",
		SiYao:           "外比於賢，以從上也",
		SiYaoJiXiong:    "吉",
		WuYao:           "顯比之吉，位正中也。舍逆取順，失前禽也。邑人不誡，上使中也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "比之無首，無所終也",
		ShangYaoJiXiong: "凶",
	}
	return gx
}

func kan(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["坎艮"] = &GuaXiang{
		ShangGua:        "坎為水",
		ShangShu:        0x05,
		XiaGua:          "艮為山",
		XiaShu:          0x06,
		GuaMing:         "水山蹇",
		ChuYao:          "往蹇來譽，宜待也",
		ChuYaoJiXiong:   "平",
		ErYao:           "王臣蹇蹇，終無尤也",
		ErYaoJiXiong:    "凶",
		SanYao:          "往蹇來反，內喜之也",
		SanYaoJiXiong:   "平",
		SiYao:           "往蹇來連，當位實也",
		SiYaoJiXiong:    "凶",
		WuYao:           "大蹇朋來，以中節也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "往蹇來碩，志在內也；利見大人，以從貴也",
		ShangYaoJiXiong: "吉",
	}

	gx["坎坎"] = &GuaXiang{
		ShangGua:        "坎為水",
		ShangShu:        0x05,
		XiaGua:          "坎為水",
		XiaShu:          0x05,
		GuaMing:         "坎為水",
		ChuYao:          "習坎入坎，失道凶也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "求小得，未出中也",
		ErYaoJiXiong:    "平",
		SanYao:          "來之坎坎，終無功也",
		SanYaoJiXiong:   "凶",
		SiYao:           "樽酒簋貳，剛柔際也",
		SiYaoJiXiong:    "平",
		WuYao:           "坎不盈，中未大也",
		WuYaoJiXiong:    "平",
		ShangYao:        "上六失道，凶三歲也",
		ShangYaoJiXiong: "凶",
	}
	gx["坎巽"] = &GuaXiang{
		ShangGua:        "坎為水",
		ShangShu:        0x05,
		XiaGua:          "巽為風",
		XiaShu:          0x04,
		GuaMing:         "水風井",
		ChuYao:          "井泥不食，下也。舊井無禽，時舍也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "井谷射鮒，無與也",
		ErYaoJiXiong:    "凶",
		SanYao:          "井渫不食，行惻也。求王明，受福也",
		SanYaoJiXiong:   "平",
		SiYao:           "井甃無咎，修井也",
		SiYaoJiXiong:    "平",
		WuYao:           "寒泉之食，中正也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "元吉在上，大成也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
	}
	gx["坎震"] = &GuaXiang{
		ShangGua:        "坎為水",
		ShangShu:        0x05,
		XiaGua:          "震為雷",
		XiaShu:          0x03,
		GuaMing:         "水雷屯",
		ChuYao:          "雖盤桓，志行正也；以貴下賤，大得民也",
		ChuYaoJiXiong:   "平",
		ErYao:           "六二之難，乘剛也；十年乃字，反常也",
		ErYaoJiXiong:    "平",
		SanYao:          "即鹿無虞，以縱禽也。君子舍之，往吝，窮也",
		SanYaoJiXiong:   "凶",
		SiYao:           "求而往，明也",
		SiYaoJiXiong:    "吉",
		WuYao:           "屯其膏，施未光也",
		WuYaoJiXiong:    "平",
		ShangYao:        "泣血漣如，何可長也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
	}

	gx["坎離"] = &GuaXiang{
		ShangGua:        "坎為水",
		ShangShu:        0x05,
		XiaGua:          "離為火",
		XiaShu:          0x02,
		GuaMing:         "水火既濟",
		ChuYao:          "曳其輪，義無咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "七日得，以中道也",
		ErYaoJiXiong:    "平",
		SanYao:          "三年克之，憊也",
		SanYaoJiXiong:   "凶",
		SiYao:           "終日戒，有所疑也",
		SiYaoJiXiong:    "平",
		WuYao:           "東鄰殺牛，不如西鄰之時也。實受其福，吉大來也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "濡其首厲，何可久也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坎兌"] = &GuaXiang{
		ShangGua:        "坎為水",
		ShangShu:        0x05,
		XiaGua:          "兌為澤",
		XiaShu:          0x01,
		GuaMing:         "水澤節",
		ChuYao:          "不出戶庭，知通塞也",
		ChuYaoJiXiong:   "平",
		ErYao:           "不出門庭，失時極也",
		ErYaoJiXiong:    "凶",
		SanYao:          "不節之嗟，又誰咎也",
		SanYaoJiXiong:   "平",
		SiYao:           "安節之亨，承上道也",
		SiYaoJiXiong:    "吉",
		WuYao:           "甘節之吉，居位中也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "苦節貞凶，其道窮也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["坎乾"] = &GuaXiang{
		ShangGua:        "坎為水",
		ShangShu:        0x05,
		XiaGua:          "乾為天",
		XiaShu:          0x00,
		GuaMing:         "水天需",
		ChuYao:          "需於郊，不犯難行也；利用恆，無咎，未失常也",
		ChuYaoJiXiong:   "平",
		ErYao:           "需於沙，衍在中也；雖小有言，以終吉也",
		ErYaoJiXiong:    "吉",
		SanYao:          "需於泥，災在外也。自我致寇，敬慎不敗也",
		SanYaoJiXiong:   "凶",
		SiYao:           "需於血，順以聽也",
		SiYaoJiXiong:    "平",
		WuYao:           "酒食貞吉，以中正也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "不速之客，敬之終吉；雖不當位，未大失也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}
	return gx
}

func xun(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["巽坤"] = &GuaXiang{
		ShangGua:        "巽為風",
		ShangShu:        0x04,
		XiaGua:          "坤為地",
		XiaShu:          0x07,
		GuaMing:         "風地觀",
		ChuYao:          "初六童觀，小人道也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "窺觀女貞，亦可醜也",
		ErYaoJiXiong:    "平",
		SanYao:          "觀我生進退，未失道也",
		SanYaoJiXiong:   "平",
		SiYao:           "觀國之光，尚賓也",
		SiYaoJiXiong:    "平",
		WuYao:           "觀我生，觀民也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "觀其生，志未平也",
		ShangYaoJiXiong: "平",
	}

	gx["巽艮"] = &GuaXiang{
		ShangGua:        "巽為風",
		ShangShu:        0x04,
		XiaGua:          "艮為山",
		XiaShu:          0x06,
		GuaMing:         "風山漸",
		ChuYao:          "小子之厲，義無咎也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "飲食衎衎，不素飽也",
		ErYaoJiXiong:    "吉",
		SanYao:          "夫徵不復，離群醜也。婦孕不育，失其道也。利用禦寇，順相保也",
		SanYaoJiXiong:   "凶",
		SiYao:           "或得其桷，順以巽也",
		SiYaoJiXiong:    "平",
		WuYao:           "終莫之勝，吉，得所願也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "其羽可用為儀，吉，不可亂也",
		ShangYaoJiXiong: "吉",
	}

	gx["巽坎"] = &GuaXiang{
		ShangGua:        "巽為風",
		ShangShu:        0x04,
		XiaGua:          "坎為水",
		XiaShu:          0x05,
		GuaMing:         "風水渙",
		ChuYao:          "初六之吉，順也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "渙奔其機，得願也",
		ErYaoJiXiong:    "平",
		SanYao:          "渙其躬，志在外也",
		SanYaoJiXiong:   "平",
		SiYao:           "渙其群，元吉，光大也",
		SiYaoJiXiong:    "吉",
		WuYao:           "王居無咎，正位也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "渙其血，遠害也",
		ShangYaoJiXiong: "平",
	}
	gx["巽巽"] = &GuaXiang{
		ShangGua:        "巽為風",
		ShangShu:        0x04,
		XiaGua:          "巽為風",
		XiaShu:          0x04,
		GuaMing:         "巽為風",
		ChuYao:          "進退，志疑也。利武人之貞，志治也",
		ChuYaoJiXiong:   "平",
		ErYao:           "紛若之吉，得中也",
		ErYaoJiXiong:    "吉",
		SanYao:          "頻巽之吝，志窮也",
		SanYaoJiXiong:   "凶",
		SiYao:           "田獲三品，有功也",
		SiYaoJiXiong:    "吉",
		WuYao:           "九五之吉，位中正也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "巽在床下，上窮也；喪其資斧，正乎凶也",
		ShangYaoJiXiong: "凶",
	}
	gx["巽震"] = &GuaXiang{
		ShangGua:        "巽為風",
		ShangShu:        0x04,
		XiaGua:          "震為雷",
		XiaShu:          0x03,
		GuaMing:         "風雷益",
		ChuYao:          "元吉無咎，下不厚事也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "或益之，自外來也",
		ErYaoJiXiong:    "吉",
		SanYao:          "益用凶事，固有之也",
		SanYaoJiXiong:   "平",
		SiYao:           "告公從，以益志也",
		SiYaoJiXiong:    "平",
		WuYao:           "有孚惠心，勿問之矣。惠我德，大得志也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "莫益之，偏辭也。或擊之，自外來也",
		ShangYaoJiXiong: "凶",
	}

	gx["巽離"] = &GuaXiang{
		ShangGua:        "巽為風",
		ShangShu:        0x04,
		XiaGua:          "離為火",
		XiaShu:          0x02,
		GuaMing:         "風火家人",
		ChuYao:          "閒有家，志未變也",
		ChuYaoJiXiong:   "平",
		ErYao:           "六二之吉，順以巽也",
		ErYaoJiXiong:    "吉",
		SanYao:          "家人嗃嗃，未失也；婦子嘻嘻，失家節也",
		SanYaoJiXiong:   "凶",
		SiYao:           "富家大吉，順在位也",
		SiYaoJiXiong:    "吉",
		WuYao:           "王假有家，交相愛也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "威如之吉，反身之謂也",
		ShangYaoJiXiong: "吉",
	}

	gx["巽兌"] = &GuaXiang{
		ShangGua:        "巽為風",
		ShangShu:        0x04,
		XiaGua:          "兌為澤",
		XiaShu:          0x01,
		GuaMing:         "風澤中孚",
		ChuYao:          "初九虞吉，志未變也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "其子和之，中心願也",
		ErYaoJiXiong:    "吉",
		SanYao:          "或鼓或罷，位不當也",
		SanYaoJiXiong:   "凶",
		SiYao:           "馬匹亡，絕類上也",
		SiYaoJiXiong:    "平",
		WuYao:           "有孚攣如，位正當也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "翰音登於天，何可長也",
		ShangYaoJiXiong: "凶",
	}
	gx["巽乾"] = &GuaXiang{
		ShangGua:        "巽為風",
		ShangShu:        0x04,
		XiaGua:          "乾為天",
		XiaShu:          0x00,
		GuaMing:         "風天小畜",
		ChuYao:          "復自道，其義吉也",
		ChuYaoJiXiong:   "平",
		ErYao:           "牽覆在中，亦不自失也",
		ErYaoJiXiong:    "吉",
		SanYao:          "夫妻反目，不能正室也",
		SanYaoJiXiong:   "凶",
		SiYao:           "有孚惕出，上合志也",
		SiYaoJiXiong:    "平",
		WuYao:           "有孚攣如，不獨富也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "既雨既處，德積載也。君子徵凶，有所疑也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}
	return gx
}

func zhen(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["震坤"] = &GuaXiang{
		ShangGua:        "震為雷",
		ShangShu:        0x03,
		XiaGua:          "坤為地",
		XiaShu:          0x07,
		GuaMing:         "雷地豫",
		ChuYao:          "初六鳴豫，志窮凶也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "不終日，貞吉，以中正也",
		ErYaoJiXiong:    "吉",
		SanYao:          "盱豫有悔，位不當也",
		SanYaoJiXiong:   "凶",
		SiYao:           "由豫大有得。志大行也",
		SiYaoJiXiong:    "吉",
		WuYao:           "六五貞疾，乘剛也。恆不死，中未亡也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "冥豫在上，何可長也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["震艮"] = &GuaXiang{
		ShangGua:        "震為雷",
		ShangShu:        0x03,
		XiaGua:          "艮為山",
		XiaShu:          0x06,
		GuaMing:         "雷山小過",
		ChuYao:          "飛鳥以凶，不可如何也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "不及其君，臣不可過也",
		ErYaoJiXiong:    "平",
		SanYao:          "從或戕之，凶如何也",
		SanYaoJiXiong:   "凶",
		SiYao:           "弗過遇之，位不當也。往厲必戒，終不可長也",
		SiYaoJiXiong:    "平",
		WuYao:           "密雲不雨，已上也",
		WuYaoJiXiong:    "平",
		ShangYao:        "弗遇過之，已亢也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["震坎"] = &GuaXiang{
		ShangGua:        "震為雷",
		ShangShu:        0x03,
		XiaGua:          "坎為水",
		XiaShu:          0x05,
		GuaMing:         "雷水解",
		ChuYao:          "剛柔之際，義無咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "九二貞吉，得中道也",
		ErYaoJiXiong:    "吉",
		SanYao:          "負且乘，亦可醜也；自我致戎，又誰咎也",
		SanYaoJiXiong:   "凶",
		SiYao:           "解而拇，未當位也",
		SiYaoJiXiong:    "凶",
		WuYao:           "君子有解，小人退也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "公用射隼，以解悖也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
		YongJiXiong:     "",
	}
	gx["震巽"] = &GuaXiang{
		ShangGua:        "震為雷",
		ShangShu:        0x03,
		XiaGua:          "巽為風",
		XiaShu:          0x04,
		GuaMing:         "雷風恆",
		ChuYao:          "浚恆之凶，始求深也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "九二悔亡，能久中也",
		ErYaoJiXiong:    "平",
		SanYao:          "不恆其德，無所容也",
		SanYaoJiXiong:   "凶",
		SiYao:           "久非其位，安得禽也",
		SiYaoJiXiong:    "凶",
		WuYao:           "婦人貞吉，從一而終也。夫子制義，從婦凶也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "振恆在上，大無功也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}
	gx["震震"] = &GuaXiang{
		ShangGua:        "震為雷",
		ShangShu:        0x03,
		XiaGua:          "震為雷",
		XiaShu:          0x03,
		GuaMing:         "震為雷",
		ChuYao:          "震來虩虩，恐致福也。笑言啞啞，後有則也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "震來厲，乘剛也",
		ErYaoJiXiong:    "凶",
		SanYao:          "震蘇蘇，位不當也",
		SanYaoJiXiong:   "凶",
		SiYao:           "震遂泥，未光也",
		SiYaoJiXiong:    "凶",
		WuYao:           "震往來厲，危行也。其事在中，大無喪也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "震索索，未得中也。雖凶無咎，畏鄰戒也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["震離"] = &GuaXiang{
		ShangGua:        "震為雷",
		ShangShu:        0x03,
		XiaGua:          "離為火",
		XiaShu:          0x02,
		GuaMing:         "雷火豐",
		ChuYao:          "雖旬無咎，過旬災也",
		ChuYaoJiXiong:   "平",
		ErYao:           "有孚發若，信以發志也",
		ErYaoJiXiong:    "吉",
		SanYao:          "豐其沛，不可大事也。折其右肱，終不可用也",
		SanYaoJiXiong:   "平",
		SiYao:           "豐其蔀，位不當也。日中見鬥，幽不明也。遇其夷主，吉，行也",
		SiYaoJiXiong:    "平",
		WuYao:           "六五之吉，有慶也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "豐其屋，天際翔也。窺其戶，闃其無人，自藏也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["震兌"] = &GuaXiang{
		ShangGua:        "震為雷",
		ShangShu:        0x03,
		XiaGua:          "兌為澤",
		XiaShu:          0x01,
		GuaMing:         "雷澤歸妹",
		ChuYao:          "歸妹以娣，以恆也。跛能履吉，相承也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "利幽人之貞，未變常也",
		ErYaoJiXiong:    "平",
		SanYao:          "歸妹以須，未當也",
		SanYaoJiXiong:   "凶",
		SiYao:           "愆期之志，有待而行也",
		SiYaoJiXiong:    "平",
		WuYao:           "帝乙歸妹，不如其娣之袂良也。其位在中，以貴行也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "上六無實，承虛筐也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}
	gx["震乾"] = &GuaXiang{
		ShangGua:        "震為雷",
		ShangShu:        0x03,
		XiaGua:          "乾為天",
		XiaShu:          0x00,
		GuaMing:         "雷天大壯",
		ChuYao:          "壯於趾，其孚窮也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "九二貞吉，以中也",
		ErYaoJiXiong:    "吉",
		SanYao:          "小人用壯，君子罔也",
		SanYaoJiXiong:   "凶",
		SiYao:           "藩決不羸，尚往也",
		SiYaoJiXiong:    "吉",
		WuYao:           "喪羊於易，位不當也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "不能退，不能遂，不詳也；艱則吉，咎不長也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}
	return gx
}

func li(gx map[string]*GuaXiang) map[string]*GuaXiang {

	gx["離坤"] = &GuaXiang{
		ShangGua:        "離為火",
		ShangShu:        0x02,
		XiaGua:          "坤為地",
		XiaShu:          0x07,
		GuaMing:         "火地晉",
		ChuYao:          "晉如摧如，獨行正也。裕無咎，未受命也",
		ChuYaoJiXiong:   "平",
		ErYao:           "受之介福，以中正也",
		ErYaoJiXiong:    "吉",
		SanYao:          "眾允之，志上行也",
		SanYaoJiXiong:   "平",
		SiYao:           "鼫鼠貞厲，位不當也",
		SiYaoJiXiong:    "凶",
		WuYao:           "失得勿恤，往有慶也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "維用伐邑，道未光也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["離艮"] = &GuaXiang{
		ShangGua:        "離為火",
		ShangShu:        0x02,
		XiaGua:          "艮為山",
		XiaShu:          0x06,
		GuaMing:         "火山旅",
		ChuYao:          "旅瑣瑣，志窮災也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "得童僕貞，終無尤也",
		ErYaoJiXiong:    "吉",
		SanYao:          "旅焚其次，亦以傷矣。以旅與下，其義喪也",
		SanYaoJiXiong:   "凶",
		SiYao:           "旅於處，未得位也。得其資斧，心未快也",
		SiYaoJiXiong:    "凶",
		WuYao:           "終以譽命，上逮也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "以旅在上，其義焚也。喪牛於易，終莫之聞也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["離坎"] = &GuaXiang{
		ShangGua:        "離為火",
		ShangShu:        0x02,
		XiaGua:          "坎為水",
		XiaShu:          0x05,
		GuaMing:         "火水未濟",
		ChuYao:          "濡其尾，亦不知極也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "九二貞吉，中以行正也",
		ErYaoJiXiong:    "吉",
		SanYao:          "未濟徵凶，位不當也",
		SanYaoJiXiong:   "凶",
		SiYao:           "貞吉悔亡，志行也",
		SiYaoJiXiong:    "吉",
		WuYao:           "君子之光，其暉吉也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "飲酒濡首，亦不知節也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["離巽"] = &GuaXiang{
		ShangGua:        "離為火",
		ShangShu:        0x02,
		XiaGua:          "巽為風",
		XiaShu:          0x04,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "火風鼎",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "鼎顛趾，未悖也。利出否，以從貴也",
		ChuYaoJiXiong:   "平",
		ErYao:           "鼎有實，慎所之也。我仇有疾，終無尤也",
		ErYaoJiXiong:    "吉",
		SanYao:          "鼎耳革，失其義也",
		SanYaoJiXiong:   "平",
		SiYao:           "覆公餗，信如何也",
		SiYaoJiXiong:    "凶",
		WuYao:           "鼎黃耳，中以為實也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "玉鉉在上，剛柔節也",
		ShangYaoJiXiong: "吉 ",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["離震"] = &GuaXiang{
		ShangGua:        "離為火",
		ShangShu:        0x02,
		XiaGua:          "震為雷",
		XiaShu:          0x03,
		GuaMing:         "火雷噬嗑",
		ChuYao:          "屨校滅趾，不行也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "噬膚滅鼻，乘剛也",
		ErYaoJiXiong:    "平",
		SanYao:          "遇毒，位不當也",
		SanYaoJiXiong:   "凶",
		SiYao:           "利艱貞吉，未光也",
		SiYaoJiXiong:    "吉",
		WuYao:           "貞厲無咎，得當也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "何校滅耳，聰不明也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["離離"] = &GuaXiang{
		ShangGua:        "離為火",
		ShangShu:        0x02,
		XiaGua:          "離為火",
		XiaShu:          0x02,
		GuaMing:         "離為火",
		ChuYao:          "履錯之敬，以闢咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "黃離元吉，得中道也",
		ErYaoJiXiong:    "吉",
		SanYao:          "日昃之離，何可久也",
		SanYaoJiXiong:   "凶",
		SiYao:           "突如其來如，無所容也",
		SiYaoJiXiong:    "凶",
		WuYao:           "六五之吉，離王公也",
		WuYaoJiXiong:    "平",
		ShangYao:        "王用出徵，以正邦也",
		ShangYaoJiXiong: "吉 ",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["離兌"] = &GuaXiang{
		ShangGua:        "離為火",
		ShangShu:        0x02,
		XiaGua:          "兌為澤",
		XiaShu:          0x01,
		GuaMing:         "火澤睽",
		ChuYao:          "見惡人，以闢咎也",
		ChuYaoJiXiong:   "平",
		ErYao:           "遇主於巷，未失道也",
		ErYaoJiXiong:    "平",
		SanYao:          "見輿曳，位不當也；無初有終，遇剛也",
		SanYaoJiXiong:   "凶",
		SiYao:           "交孚無咎，志行也",
		SiYaoJiXiong:    "平",
		WuYao:           "厥宗噬膚，往有慶也",
		WuYaoJiXiong:    "平",
		ShangYao:        "遇雨之吉，群疑亡也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["離乾"] = &GuaXiang{
		ShangGua:        "離為火",
		ShangShu:        0x02,
		XiaGua:          "乾為天",
		XiaShu:          0x00,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "火天大有",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "大有初九，無交害也",
		ChuYaoJiXiong:   "平",
		ErYao:           "大車以載，積中不敗也",
		ErYaoJiXiong:    "吉",
		SanYao:          "公用亨於天子，小人害也",
		SanYaoJiXiong:   "平",
		SiYao:           "匪其彭，無咎，明辯晰也",
		SiYaoJiXiong:    "平",
		WuYao:           "厥孚交如，信以發志也；威如之吉，易而無備也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "大有上吉，自天祐也",
		ShangYaoJiXiong: "吉",
		Yong:            "",
		YongJiXiong:     "",
	}
	return gx
}

func dui(gx map[string]*GuaXiang) map[string]*GuaXiang {
	gx["兌坤"] = &GuaXiang{
		ShangGua:        "兌為澤",
		ShangShu:        0x01,
		XiaGua:          "坤為地",
		XiaShu:          0x07,
		GuaMing:         "澤地萃",
		ChuYao:          "乃亂乃萃，其志亂也",
		ChuYaoJiXiong:   "平",
		ErYao:           "引吉無咎，中未變也",
		ErYaoJiXiong:    "吉",
		SanYao:          "往無咎，上巽也",
		SanYaoJiXiong:   "凶",
		SiYao:           "大吉無咎，位不當也",
		SiYaoJiXiong:    "平",
		WuYao:           "萃有位，志未光也",
		WuYaoJiXiong:    "平",
		ShangYao:        "齎諮涕洟，未安上也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兌艮"] = &GuaXiang{
		ShangGua:        "兌為澤",
		ShangShu:        0x01,
		XiaGua:          "艮為山",
		XiaShu:          0x06,
		JiXiong:         "吉",
		GuaXiang:        "山上有澤，鹹。君子以虛受人",
		GuaMing:         "澤山鹹",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "鹹其拇，志在外也",
		ChuYaoJiXiong:   "平",
		ErYao:           "雖凶居吉，順不害也",
		ErYaoJiXiong:    "平",
		SanYao:          "鹹其股，亦不處也。志在隨人，所執下也",
		SanYaoJiXiong:   "平",
		SiYao:           "貞吉悔亡，未感害也。憧憧往來，未光大也",
		SiYaoJiXiong:    "平",
		WuYao:           "鹹其脢，志末也",
		WuYaoJiXiong:    "平",
		ShangYao:        "鹹其輔頰舌，滕口說也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兌坎"] = &GuaXiang{
		ShangGua:        "兌為澤",
		ShangShu:        0x01,
		XiaGua:          "坎為水",
		XiaShu:          0x05,
		GuaMing:         "澤水困",
		ChuYao:          "入於幽谷，幽不明也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "困於灑食，中有慶也",
		ErYaoJiXiong:    "平",
		SanYao:          "據於疾藜，乘剛也；入於其宮，不見其妻，不祥也",
		SanYaoJiXiong:   "凶",
		SiYao:           "來徐徐，志在下也。雖不當位，有與也",
		SiYaoJiXiong:    "凶",
		WuYao:           "劓刖，志未得也。乃徐有說，以中直也。利用祭祀，受福也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "困於葛藟，未當也。動悔有悔，吉行也",
		ShangYaoJiXiong: "平",
	}

	gx["兌巽"] = &GuaXiang{
		ShangGua:        "兌為澤",
		ShangShu:        0x01,
		XiaGua:          "巽為風",
		XiaShu:          0x04,
		GuaMing:         "澤風大過",
		ChuYao:          "藉用白茅，柔在下也",
		ChuYaoJiXiong:   "平",
		ErYao:           "老夫女妻，過以相與也",
		ErYaoJiXiong:    "吉",
		SanYao:          "棟橈之凶，不可以有輔也",
		SanYaoJiXiong:   "凶",
		SiYao:           "棟隆之吉，不橈乎下也",
		SiYaoJiXiong:    "吉",
		WuYao:           "枯楊生花，何可久也。老婦土夫，亦可醜也",
		WuYaoJiXiong:    "平",
		ShangYao:        "過涉之凶，不可咎也",
		ShangYaoJiXiong: "凶",
	}

	gx["兌震"] = &GuaXiang{
		ShangGua:        "兌為澤",
		ShangShu:        0x01,
		XiaGua:          "震為雷",
		XiaShu:          0x03,
		GuaMing:         "澤雷隨",
		ChuYao:          "官有渝，從正吉也；出門交有功，不失也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "系小子，弗兼與也",
		ErYaoJiXiong:    "凶",
		SanYao:          "系丈夫，志舍下也",
		SanYaoJiXiong:   "平",
		SiYao:           "隨有獲，其義凶也。有孚在道，明功也",
		SiYaoJiXiong:    "平",
		WuYao:           "孚於嘉吉，位正中也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "拘繫之，上窮也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兌離"] = &GuaXiang{
		ShangGua:        "兌為澤",
		ShangShu:        0x01,
		XiaGua:          "離為火",
		XiaShu:          0x02,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "澤火革",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "鞏用黃牛，不可以有為也",
		ChuYaoJiXiong:   "平",
		ErYao:           "己日革之，行有嘉也",
		ErYaoJiXiong:    "吉",
		SanYao:          "革言三就，又何之矣",
		SanYaoJiXiong:   "凶",
		SiYao:           "改命之吉，信志也",
		SiYaoJiXiong:    "平",
		WuYao:           "大人虎變，其文炳也",
		WuYaoJiXiong:    "吉",
		ShangYao:        "君子豹變，其文蔚也。小人革面，順以從君也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兌兌"] = &GuaXiang{
		ShangGua:        "兌為澤",
		ShangShu:        0x01,
		XiaGua:          "兌為澤",
		XiaShu:          0x01,
		JiXiong:         "吉",
		GuaXiang:        "麗澤，兌。君子以朋友講習",
		GuaMing:         "兌為澤",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "和兌之吉，行未疑也",
		ChuYaoJiXiong:   "吉",
		ErYao:           "孚兌之吉，信志也",
		ErYaoJiXiong:    "吉",
		SanYao:          "來兌之凶，位不當也",
		SanYaoJiXiong:   "凶",
		SiYao:           "九四之喜，有慶也",
		SiYaoJiXiong:    "平",
		WuYao:           "孚於剝，位正當也",
		WuYaoJiXiong:    "凶",
		ShangYao:        "上六引兌，未光也",
		ShangYaoJiXiong: "平",
		Yong:            "",
		YongJiXiong:     "",
	}

	gx["兌乾"] = &GuaXiang{
		ShangGua:        "兌為澤",
		ShangShu:        0x01,
		XiaGua:          "乾為天",
		XiaShu:          0x00,
		JiXiong:         "",
		GuaXiang:        "",
		GuaMing:         "澤天夬",
		GuaYi:           "",
		GuaYun:          "",
		XiangYue:        "",
		FuHao:           "",
		ChuYao:          "不勝而往，咎也",
		ChuYaoJiXiong:   "凶",
		ErYao:           "有戎勿恤，得中道也",
		ErYaoJiXiong:    "凶",
		SanYao:          "君子夬夬，終無咎也",
		SanYaoJiXiong:   "凶",
		SiYao:           "其行次且，位不當也；聞言不信，聰不明也",
		SiYaoJiXiong:    "凶",
		WuYao:           "中行無咎，中未光也",
		WuYaoJiXiong:    "平",
		ShangYao:        "無號之凶，終不可長也",
		ShangYaoJiXiong: "凶",
		Yong:            "",
		YongJiXiong:     "",
	}

	return gx
}

func TestSetGuaXiang(t *testing.T) {
	gx := make(map[string]*GuaXiang)
	gx = qian(gx)
	gx = kun(gx)
	gx = gen(gx)
	gx = kan(gx)
	gx = xun(gx)
	gx = zhen(gx)
	gx = li(gx)
	gx = dui(gx)
	setGuaXiang(gx)

}

func TestGetGuaXiang(t *testing.T) {
	if len(GetGuaXiang()) != 64 {
		t.Log("not enough", GetGuaXiang())
	}

}
